// =============================================================================
// PETRICHOR — STYLE DICTIONARY CONFIG
// =============================================================================
// Transforms YAML token schema into:
//   dist/css/base.css              — system tokens as CSS custom properties
//   dist/css/brand.raindrop.css    — Raindrop brand overrides
//   dist/css/brand.dusk-rose.css   — Dusk Rose brand overrides
//   dist/js/tokens.js              — ES module token object
//   dist/js/tokens.cjs             — CommonJS token object
//   dist/ts/tokens.d.ts            — TypeScript declarations
//
// Usage: node style-dictionary.config.js
// =============================================================================

import StyleDictionary from 'style-dictionary';
import { readFileSync, copyFileSync, mkdirSync } from 'fs';
import { load } from 'js-yaml';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

// ---------------------------------------------------------------------------
// Custom YAML parser — Style Dictionary reads JSON by default
// ---------------------------------------------------------------------------

StyleDictionary.registerParser({
	name: 'yaml-parser',
	pattern: /\.ya?ml$/,
	parser: ({ contents }) => load(contents),
});

// ---------------------------------------------------------------------------
// Custom transform — convert token path to CSS variable name
// e.g. color.brand.primary → --ptr-color-brand-primary
// ---------------------------------------------------------------------------

StyleDictionary.registerTransform({
	name: 'name/ptr/css',
	type: 'name',
	transform: (token) => {
		return `ptr-${token.path.join('-')}`;
	},
});

// ---------------------------------------------------------------------------
// Custom format — CSS custom properties with theme scoping
// ---------------------------------------------------------------------------

StyleDictionary.registerFormat({
	name: 'css/ptr-variables',
	format: ({ dictionary, options }) => {
		const selector = options.selector ?? ':root';
		const vars = dictionary.allTokens
			.map((token) => `  --${token.name}: ${token.value};`)
			.join('\n');

		const header = [
			`/* =========================================================`,
			` * Petrichor Design System — ${options.brand ?? 'Base'} Tokens`,
			` * Generated by Style Dictionary — DO NOT EDIT DIRECTLY`,
			` * Edit source: packages/tokens/src/tokens/`,
			` * ========================================================= */`,
		].join('\n');

		const fontImports = (options.fontImports ?? [])
			.map((url) => `@import url('${url}');`)
			.join('\n');

		const preamble = fontImports ? `${fontImports}\n\n` : '';

		return `${header}\n\n${preamble}${selector} {\n${vars}\n}\n`;
	},
});

// ---------------------------------------------------------------------------
// Token sources — base files shared across all builds
// ---------------------------------------------------------------------------

const baseSources = [
	join(__dirname, 'src/tokens/base.yaml'),
	join(__dirname, 'src/tokens/semantic.yaml'),
];

// ---------------------------------------------------------------------------
// Build configurations
// ---------------------------------------------------------------------------

const transforms = ['name/ptr/css', 'time/seconds', 'size/px', 'color/css'];

// 1. Base system tokens — no brand applied
const baseConfig = {
	source: baseSources,
	parsers: ['yaml-parser'],
	platforms: {
		css: {
			transforms,
			prefix: 'ptr',
			buildPath: 'dist/css/',
			files: [
				{
					destination: 'base.css',
					format: 'css/ptr-variables',
					options: {
						selector: ':root',
						brand: 'Base system',
						fontImports: [
							'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap',
						],
					},
				},
			],
		},
		js: {
			transforms,
			buildPath: 'dist/js/',
			files: [
				{
					destination: 'tokens.js',
					format: 'javascript/esm',
				},
				{
					destination: 'tokens.cjs',
					format: 'javascript/module-flat',
				},
			],
		},
		// ts: {
		// 	transforms,
		// 	buildPath: 'dist/ts/',
		// 	files: [
		// 		{
		// 			destination: 'tokens.d.ts',
		// 			format: 'typescript/module-declarations',
		// 		},
		// 	],
		// },
	},
};

// 2. Raindrop brand — base + raindrop overrides
const raindropConfig = {
	source: [
		...baseSources,
		join(__dirname, 'src/tokens/brands/raindrop.yaml'),
	],
	parsers: ['yaml-parser'],
	platforms: {
		css: {
			transforms,
			prefix: 'ptr',
			buildPath: 'dist/css/',
			files: [
				{
					destination: 'brand.raindrop.css',
					format: 'css/ptr-variables',
					options: {
						// Scoped to data attribute — apply to root element of brand app
						selector: '[data-brand="raindrop"]',
						brand: 'Raindrop',
					},
				},
			],
		},
	},
};

// 3. Dusk Rose brand — base + dusk-rose overrides
const duskRoseConfig = {
	source: [
		...baseSources,
		join(__dirname, 'src/tokens/brands/dusk-rose.yaml'),
	],
	parsers: ['yaml-parser'],
	platforms: {
		css: {
			transforms,
			prefix: 'ptr',
			buildPath: 'dist/css/',
			files: [
				{
					destination: 'brand.dusk-rose.css',
					format: 'css/ptr-variables',
					options: {
						selector: '[data-brand="dusk-rose"]',
						brand: 'Dusk Rose',
						fontImports: [
							'https://api.fontshare.com/v2/css?f[]=cabinet-grotesk@400,500,700&display=swap',
							'https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,700;1,9..144,400;1,9..144,700&display=swap',
						],
					},
				},
			],
		},
	},
};

// ---------------------------------------------------------------------------
// Run all builds
// ---------------------------------------------------------------------------

async function build() {
	console.log('\n🌧  Petrichor — building tokens...\n');

	for (const [name, config] of [
		['Base', baseConfig],
		['Raindrop', raindropConfig],
		['Dusk Rose', duskRoseConfig],
	]) {
		const sd = new StyleDictionary(config);
		await sd.buildAllPlatforms();
		console.log(`  ✓ ${name}`);
	}

	// Copy static CSS files
	mkdirSync('dist/css', { recursive: true });
	copyFileSync(
		join(__dirname, 'src/css/light.css'),
		join(__dirname, 'dist/css/light.css'),
	);
	console.log('  ✓ Light mode');

	console.log('\n✨ Done. Output in dist/\n');
}

build().catch((err) => {
	console.error('Build failed:', err);
	process.exit(1);
});
